import {
    LayoutDashboard,
    LucideIcon,
    Settings,
    User,
    GalleryVerticalEnd,
    AppWindow,
    Plus,
    Check,
    ArrowLeft,
    ArrowRight,
    ChevronLeft,
    Loader2,
    X,
    CheckCircle,
    Info,
    AlertTriangle,
    XOctagon,
    MoreVertical,
    Trash2,
    ChevronRight,
    Search,
} from "lucide-react";

export const Icons: { [key: string]: LucideIcon } = {
    settings: Settings,
    user: User,
    dashboard: LayoutDashboard,
    page: AppWindow,
    popup: GalleryVerticalEnd,
    add: Plus,
    check: Check,
    success: CheckCircle,
    info: Info,
    warning: AlertTriangle,
    error: XOctagon,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    spinner: Loader2,
    trash: Trash2,
    x: X,
    moreVertical: MoreVertical,
    search: Search,
};
